language: node_js
node_js:
  - "4"
  - "6"
  - "node"
  - "iojs"
  - "0.12"
  - "0.8"
script:
  - npm run build && npm run lint && npm test -- --coverage
cache:
  - yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)
