const {Transform} = require('stream');

const HEADER = `# THIS IS AN AUTO-GENERATED FILE
# DO NOT EDIT THIS FILE DIRECTLY
# To update this file, run the appropriate script in the scripts/ directory
module.exports = \``;
const FOOTER = '`\n';

/**
 * Wraps a stream in Javascript so that it can be required by node and other
 * node.js tools.
 */
class RequireTransform extends Transform {
  constructor() {
    // don't turn source data into a buffer unnecessarily
    super({
      decodeStrings: false,
    });
  }

  _transform(chunk, encoding, done) {
    const content = encoding === 'utf8' ? chunk : chunk.toString();
    done(null, HEADER + content + FOOTER);
  }
}

module.exports = RequireTransform;
